ARTICLE_COUNT_SPAN: lx-pagination__page-number qa-pagination-total-page-number
HEADLINE_SPAN_CLASS_A: bbc-13dm3d0 e1yj3cbb0
HEADLINE_SPAN_CLASS_B: e8stly50 bbc-kqut3h e14hemmw1
HOMEPAGE: https://www.bbc.com/gahuza
TOPIC_LIST_CLASS: bbc-qbu3pw e1hq59l0
STORY_DIV_CLASS: bbc-19j92fr e57qer20
CATEGORY_URLS:
  IBIYAGA: https://www.bbc.com/gahuza/topics/c06gq67y3w5t
  AFRIKA: https://www.bbc.com/gahuza/topics/c06gq67y3w5t
  MPUZAMAHANGA: https://www.bbc.com/gahuza/topics/c9dvd93jjkkt
  IMIKINO: https://www.bbc.com/gahuza/topics/c5qvpq0jzy7t
  UBURAYI: https://www.bbc.com/gahuza/topics/c340q41gg6vt
  UBURUSIYA: https://www.bbc.com/gahuza/topics/cnq68qdw4kyt
  UKRAINE: https://www.bbc.com/gahuza/topics/cr50y5d512xt
  UBUMUNAKO: https://www.bbc.com/gahuza/topics/cvjp2jy1pj0t
  AZIYA: https://www.bbc.com/gahuza/topics/cdr56rz2p4vt
  AMAGURU: https://www.bbc.com/gahuza/topics/cz74k72rq9pt
  UBUZIMA: https://www.bbc.com/gahuza/topics/cnq68qp4kxjt
  INDYO: https://www.bbc.com/gahuza/topics/cnq68qpjpvgt
  YEPFO: https://www.bbc.com/gahuza/topics/cyx5kxdz6vgt
  UMURYANGO: https://www.bbc.com/gahuza/topics/cvjp2jy8y32t
  INKINGO: https://www.bbc.com/gahuza/topics/c340q41dg2nt
  AFURIKA: https://www.bbc.com/gahuza/topics/c06gq67yrk1t
  IKORESHWA: https://www.bbc.com/gahuza/topics/cr50y5gpkykt
  COLOMBIA: https://www.bbc.com/gahuza/topics/c340q4vk27jt
  KONGO: https://www.bbc.com/gahuza/topics/c8y94y03z72t
  POLITIKE: https://www.bbc.com/gahuza/topics/c5qvpq5ppqpt
  ABAGORE: https://www.bbc.com/gahuza/topics/c2dwqd7p2dyt
  AMERIKA: https://www.bbc.com/gahuza/topics/c2dwqd0k456t
  AMATEGEKO: https://www.bbc.com/gahuza/topics/c06gq6n0q88t
  RWANDA: https://www.bbc.com/gahuza/topics/c340q4v3942t
