ARTICLE_COUNT_SPAN: lx-pagination__page-number qa-pagination-total-page-number
HEADLINE_SPAN_CLASS_A: bbc-944mpi e1yj3cbb0
HEADLINE_SPAN_CLASS_B: bbc-944mpi e1yj3cbb0
STORY_DIV_CLASS: bbc-19j92fr e57qer20 
CATEGORY_URLS:
  CATEGORY_ONE: https://www.bbc.com/amharic/topics/c7zp57r92v5t
  MOST_POPULAR: https://www.bbc.com/amharic/popular/read