ARTICLE_COUNT_SPAN: "bbc-f8df6t e19602dz4"
HEADLINE_SPAN_CLASS_A: "bbc-csfh25 e1p3vdyi0"
HEADLINE_SPAN_CLASS_B: "ewk8wmc0 bbc-12j4rku eglt09e1"
STORY_DIV_CLASS: "bbc-19j92fr ebmt73l0"
TOPIC_LIST_CLASS: "bbc-ekyvwt e2o6ii40"

HOMEPAGE:
  sw: https://www.bbc.com/swahili/

CATEGORY_URLS:
  sw:
    MICHEZO: https://www.bbc.com/swahili/topics/ckdxndddjkxt
    VIDEO: https://www.bbc.com/swahili/media/video
  