ARTICLE_COUNT_SPAN: lx-pagination__page-number qa-pagination-total-page-number 
HEADLINE_SPAN_CLASS_A: bbc-13dm3d0 e1yj3cbb0
HEADLINE_SPAN_CLASS_B: e8stly50 bbc-kqut3h e14hemmw1
STORY_DIV_CLASS: bbc-19j92fr e57qer20 
CATEGORY_URLS:
  WASANNI: https://www.bbc.com/hausa/topics/cz74kjgv220t
  NISHADI: https://www.bbc.com/hausa/topics/cg726kz37wdt
  RAHOTANI: https://www.bbc.com/hausa/52140979
  BIDIYO: https://www.bbc.com/hausa/media/video
  MUSAMMAN: https://www.bbc.com/hausa/shirye-shirye-na-musamman-54712348
  