ARTICLE_COUNT_SPAN: lx-pagination__page-number qa-pagination-total-page-number
HEADLINE_SPAN_CLASS_A: bbc-13dm3d0 e1yj3cbb0
HEADLINE_SPAN_CLASS_B: e8stly50 bbc-kqut3h e14hemmw1
HOMEPAGE: https://www.bbc.com/yoruba
TOPIC_LIST_CLASS: bbc-qbu3pw e1hq59l0
STORY_DIV_CLASS: bbc-19j92fr e57qer20 
CATEGORY_URLS:
  IDARAYA: https://www.bbc.com/yoruba/topics/c340q0y3p5kt
  GBAJUMO: https://www.bbc.com/yoruba/popular/read