ARTICLE_COUNT_SPAN: lx-pagination__page-number qa-pagination-total-page-number
HEADLINE_SPAN_CLASS_A: bbc-13dm3d0 e1yj3cbb0
HEADLINE_SPAN_CLASS_B: e8stly50 bbc-kqut3h e14hemmw1
STORY_DIV_CLASS: bbc-19j92fr e57qer20
HOMEPAGE: https://www.bbc.com/somali
TOPIC_LIST_CLASS: bbc-qbu3pw e1hq59l0
CATEGORY_URLS:
  GANACSI: https://www.bbc.com/somali/topics/c2dwqd32v4yt
  CIYAARAHA: https://www.bbc.com/somali/topics/cpzd4zj1pn2t
  AQOON-GUUD: https://www.bbc.com/somali/topics/cg8382rk20xt
