ARTICLE_COUNT_SPAN: lx-pagination__page-number qa-pagination-total-page-number
HEADLINE_SPAN_CLASS_A: bbc-13dm3d0 e1yj3cbb0
HEADLINE_SPAN_CLASS_B: e8stly50 bbc-kqut3h e14hemmw1 # e8stly50 bbc-1joh6wp e14hemmw1
STORY_DIV_CLASS: bbc-19j92fr e57qer20
HOMEPAGE: https://www.bbc.com/afaanoromoo
TOPIC_LIST_CLASS: bbc-qbu3pw e1hq59l0
CATEGORY_URLS:
  UUMMATA: https://www.bbc.com/afaanoromoo/topics/c340q45x0prt
  AADAA: https://www.bbc.com/afaanoromoo/topics/c5qvpqg6g93t
  HAWAASAA: https://www.bbc.com/afaanoromoo/topics/ckdxnd85y40t
  ITOOPHIYAA: https://www.bbc.com/afaanoromoo/topics/c2dwqdy81y1t
  KORONAAVAAYIRAS: https://www.bbc.com/afaanoromoo/topics/cmnqydyjyy4t
  FAYYAA: https://www.bbc.com/afaanoromoo/topics/cqywjyx745xt
  QUUNNAMTII: https://www.bbc.com/afaanoromoo/topics/c95y35d83qrt
  KEENIYA: https://www.bbc.com/afaanoromoo/topics/c8y94yzyv5vt
  DUBARTOOTA: https://www.bbc.com/afaanoromoo/topics/c8y94yq185dt
  VIIDIYO: https://www.bbc.com/afaanoromoo/media/video
  JAJJABOO: https://www.bbc.com/afaanoromoo/popular/read
  HIYYUMMAA: https://www.bbc.com/afaanoromoo/topics/cyx5kx656zrt
  CHAAYIINAA: https://www.bbc.com/afaanoromoo/topics/cvjp2jg4v4qt
